//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddRandomValuesToToysDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toy
    {
        public int ToyID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int ManufacturerID { get; set; }
        public decimal Price { get; set; }
        public string Color { get; set; }
        public int AgeRangeID { get; set; }
    
        public virtual AgeRanx AgeRanx { get; set; }
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
