CREATE DATABASE TestDb;

USE testdb;

CREATE TABLE Logs(
	LogID int NOT NULL AUTO_INCREMENT,
	LogText varchar(1000),
	LogDate datetime,
	PRIMARY KEY (LogId, LogDate)
) PARTITION BY RANGE (YEAR(LogDate)) (
	PARTITION p0 VALUES LESS THAN (1990),
	PARTITION p1 VALUES LESS THAN (2000),
	PARTITION p2 VALUES LESS THAN (2010),
	PARTITION p3 VALUES LESS THAN MAXVALUE
);